### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by xdmx** [cloudflare/claire#12]
It would be very useful to have this addon also for Firefox, for all your users not using Chrome for various reasons

**Comment by Trozz** [comment]
this may not be sure a large piece of work since Firefox is getting [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) with Firefox 46, before that it would obviously need to be native

**Comment by terinjokes** [comment]
I have some internal branches which start to clean-up the extension. It may be possible to build off that work to build a Claire for Firefox.

**Comment by RReverser** [comment]
@terinjokes I think we might look into new Web Extensions API support in FF and see how well it works for us.

**Comment by elithrar** [comment]
https://www.extensiontest.com/test/9922a920-9303-11e7-97dd-c97ef306ba23

Mozilla's extension tester doesn't report any compatibility issues, however it does raise an XSS related warning:

```
{
  "compat": [],
  "errors": [],
  "warnings": [
    {
      "message": "Unsafe assignment to innerHTML",
      "locations": [
        {
          "file": "popup.js",
          "line": 1360
        },
        {
          "file": "popup.js",
          "line": 4869
        },
        {
          "file": "popup.js",
          "line": 6080
        }
      ]
    }
  ]
}
```

**Comment by elithrar** [comment]
Debugging further, the manifest is not compatible with Firefox.

```diff
12a13
>     "clipboardRead",
15a17
>     "webRequestBlocking",
17c19,20
<     "https://*/"
---
>     "https://*/",
>     "<all_urls>"
20,21c23
<     "scripts": ["background.js"],
<     "persistent": true
---
>     "scripts": ["background.js"]
24c26,27
<     "default_title": "Cloudflare"
---
>     "default_title": "Cloudflare",
>     "default_popup": "popup.js"
31c34,36
<   "options_page": "options.html",
---
>   "options_ui": {
>     "page": "options.html"
>   },
```

However, there's still issues with the extension failing to load its toolbar icon, which I'm debugging.

**Comment by terinjokes** [comment]
@elithrar I'm working on this.

**Comment by ngyikp** [comment]
The content script uses a Chrome-only API `chrome.loadTimes()`

<img width="738" alt="screen shot 2017-09-06 at 11 46 24 pm" src="https://user-images.githubusercontent.com/6135313/30121286-ddbdb23c-935d-11e7-8e4d-5772b99b0955.png">

It _might_ be removed on Chrome 64+ so action is needed
https://bugs.chromium.org/p/chromium/issues/detail?id=621512

**Comment by ngyikp** [comment]
I managed to convert it with a few minor problems:

* The page action icon disappears when you navigate around webpages that use `pushState` (e.g. https://html5demos.com/history/ )
* Doesn't work in private mode due to https://bugzilla.mozilla.org/show_bug.cgi?id=1329304
* The padding inside the page action is a little off if there are scrollbars showing

![claire firefox 2](https://user-images.githubusercontent.com/6135313/30129136-8967485a-9377-11e7-89b8-3a56cee83dc4.png)

The fork: https://github.com/ngyikp/claire/tree/initial-firefox-webextension

**Comment by elithrar** [comment]
Thanks @ngyikp - I believe @terinjokes is working on some larger refactors behind the scenes, but the fork should be useful in identifying the deltas between the Chrome extension API and the WebExtension API in Firefox.

**Comment by terinjokes** [comment]
I'm still working with a designer to work on a better interface for both Chrome and Firefox, and I recognize that there's some UI problems in Firefox right now, but I went ahead and published it on the [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/addon/cloudflare-claire/) site.

In tradition, the screenshots are made with the wrong browser. ;) (On a serious note, hopefully we can convince the Chrome team to accept our non-Safari screenshot in the next release)
