### ISSUE TITLE
Expects IP to be in details of webRequest but IP is optional

### ISSUE THREAD

**Issue by ChristopherHackett** [cloudflare/claire#14]
Chrome New Tab Window caused a type error ... 

![image](https://cloud.githubusercontent.com/assets/1075126/7191704/7ce2fea4-e487-11e4-968c-f12236e08469.png)

... because in  documentation about [webRequest event details](https://developer.chrome.com/extensions/webRequest#event-onCompleted) says that IP is optional in the webRequest details but it [is expected to be present](https://github.com/cloudflare/claire/blob/6f2f43721eaebdbfbf7f856ba8cd22029900c3f9/source/request.js#L196-L198) by the extension when checking if the request was IPv6 . 

Type | Name | Description
-------|----------|-----------------
string | (optional) ip | The server IP address that the request was actually sent to. Note that it may be a literal IPv6 address.

Effectively the behaviour of no icon showing on the New Tab Window (and other local content) is dependent on this error. I think the behaviour is correct but would be better if it didn't get this far.

**Comment by terinjokes** [comment]
Good point, I can fix the behavior.
