### ISSUE TITLE
WordPress site using CloudFlare plugin

### ISSUE THREAD

**Issue by bhubbard** [cloudflare/claire#25]
It would be cool if it could also report if the site is using WordPress (with WordPress Version), and if the CloudFlare WordPress plugin (with Version) is installed and activated on that site. 

The CloudFlare WordPress plugin would probably need a small update to make this idea work.

**Comment by Trozz** [comment]
any idea how the plugin could reliably ascertain the Wordpress version? I have looked at a couple of scripts that do this but they are simply using guess work based on the files that they can find.

It may be able to guess if the CloudFlare Wordpress plugin is installed by checking for the wp-content/plugins/cloudflare and possibly gain the version from the readme file if it exists but this would require performing requests against the server where as this plugin currently checks for HTTP headers.

**Comment by terinjokes** [comment]
I'm thinking this is outside the scope of Claire at this time.

**Comment by bhubbard** [comment]
I think it can be easier that that, simply have the CloudFlare WordPress Plugin add a single line to `wp_head`, such as:

`<!-- This site is optimized with the CloudFlare plugin v1.3.20 - https://wordpress.org/plugins/cloudflare/ -->`

For WordPress version, you can just check for the generator tag. There are a few other chrome extensions that already find the WordPress version. Such as this one:

https://chrome.google.com/webstore/detail/version-check-for-wordpre/hbeikkjblcogpkdnchpffgefhkilodnn?hl=en

**Comment by Trozz** [comment]
The generator tag can be removed, I checked a couple of WP sites before I responded and they had the tag removed.

The idea of adding in to the page could be workable however @terinjokes has said that he thinks this is outside of the scope of claire
