### ISSUE TITLE
A safari extension would be greatly appreciated

### ISSUE THREAD

**Issue by christopherowen** [cloudflare/claire#30]

**Comment by terinjokes** [comment]
I've looked into Safari support, it could happen after I handle Firefox.

**Comment by christopherowen** [comment]
I was not expecting such a quick response!  You guys are great.

**Comment by terinjokes** [comment]
Browser extensions on Safari are significantly less powerful, so don't expect nearly the same functionality.

**Comment by christopherowen** [comment]
just wanting to chime in that I would still find this useful

**Comment by tarunVreddy** [comment]
+1

**Comment by sssilver** [comment]
+1

**Comment by seanmmitchell** [comment]
Claire has been deprecated by **Optics**, which was launched with Manifest V3 and Firefox support.

## Downloads for Optics

[![Chrome Web Store](https://img.shields.io/chrome-web-store/v/mdjgbjnbdnhneejmmaabmccfehigbjbe.svg)](https://chrome.google.com/webstore/detail/optics/mdjgbjnbdnhneejmmaabmccfehigbjbe)
[![Firefox Add-ons](https://img.shields.io/amo/v/cloudflare-optics.svg)](https://addons.mozilla.org/firefox/addon/cloudflare-optics/)
