### ISSUE TITLE
DNSSEC support

### ISSUE THREAD

**Issue by christopherowen** [cloudflare/claire#31]
It would be nice for claire to have a status indicator for DNSSEC support/correctness.

**Comment by terinjokes** [comment]
@christopherowen You must have a list of my plans.

**Comment by christopherowen** [comment]
well, if I reach your level a third time, change your gpg keys ;).

**Comment by seanmmitchell** [comment]
Claire has been deprecated by **Optics**, which was launched with Manifest V3 and Firefox support.

## Downloads for Optics

[![Chrome Web Store](https://img.shields.io/chrome-web-store/v/mdjgbjnbdnhneejmmaabmccfehigbjbe.svg)](https://chrome.google.com/webstore/detail/optics/mdjgbjnbdnhneejmmaabmccfehigbjbe)
[![Firefox Add-ons](https://img.shields.io/amo/v/cloudflare-optics.svg)](https://addons.mozilla.org/firefox/addon/cloudflare-optics/)
