### ISSUE TITLE
Transparent background for images

### ISSUE THREAD

**Issue by benwa** [cloudflare/claire#32]
Looks like page actions are going away in some form ([source](https://groups.google.com/a/chromium.org/d/topic/chromium-extensions/7As9MKhav5E/discussion)).

With that, the white background on the toolbar looks a bit out of place.
![image](https://cloud.githubusercontent.com/assets/1351571/13467797/d41a9d70-e06d-11e5-889e-d57e62f8ccc8.png)

**Comment by terinjokes** [comment]
@benwa they went away in dev builds then came back. I still have page actions (in Chrome 50), so I'm not sure what exactly they're going to do.

In either case, there's a PR open to fix this.
