### ISSUE TITLE
Icon no longer showing in Chrome address bar

### ISSUE THREAD

**Issue by jb510** [cloudflare/claire#41]
I swear it used to show in the address bar, now it's where the rest of the extensions are and I can't figure out how to get it back.  

Was this a deliberate code change? If so, this should be updated https://github.com/cloudflare/claire#claire

If not, how do I get it back in the address bar (I'd much rather have it there)
![2016-12-23 at 5 07 pm](https://cloud.githubusercontent.com/assets/801241/21464463/6dd664be-c932-11e6-9447-f69cee1a5912.jpg)

**Comment by terinjokes** [comment]
This was removed by the Chrome team several months ago. See https://github.com/cloudflare/claire/releases/tag/v0.8.1

I'll fix the readme, I forgot that was there.
