### ISSUE TITLE
`chrome.loadTimes` is deprecated

### ISSUE THREAD

**Issue by ngyikp** [cloudflare/claire#48]
On Chrome 64.0.3260.2:

[Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.

**Comment by terinjokes** [comment]
I'll update it this week. Thanks for the notification.

**Comment by ExE-Boss** [comment]
This will also make it possible to implement this in Firefox, because [Firefox 58 supports this](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming#Browser_compatibility).

**Comment by terinjokes** [comment]
@ExE-Boss It's on my task list this week to support Quantum properly.
