### ISSUE TITLE
Formatting of popup breaks a bit if remote CSS can't be loaded

### ISSUE THREAD

**Issue by ngyikp** [cloudflare/claire#51]
<img width="900" alt="screen shot 2017-12-31 at 10 18 59 am" src="https://user-images.githubusercontent.com/6135313/34508919-c91947cc-f07f-11e7-9c78-0c2083c18883.png">

**Comment by terinjokes** [comment]
I should really bundle the CSS. Thanks for the issue!

**Comment by terinjokes** [comment]
This was fixed in v0.11.1, which was released to the Firefox marketplace, but hasn't yet gone out to Chrome's.

**Comment by seanmmitchell** [comment]
Claire has been deprecated by **Optics**, which was launched with Manifest V3 and Firefox support.

## Downloads for Optics

[![Chrome Web Store](https://img.shields.io/chrome-web-store/v/mdjgbjnbdnhneejmmaabmccfehigbjbe.svg)](https://chrome.google.com/webstore/detail/optics/mdjgbjnbdnhneejmmaabmccfehigbjbe)
[![Firefox Add-ons](https://img.shields.io/amo/v/cloudflare-optics.svg)](https://addons.mozilla.org/firefox/addon/cloudflare-optics/)
