### ISSUE TITLE
Claire fails to install on Nightly 62

### ISSUE THREAD

**Issue by alex-mayorga** [cloudflare/claire#54]
Claire fails to install on Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0 ID:20180522100110

Here's what got logged into the "Browser Console":

Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: ;undefined. claire:1
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src”). Source: height:0. cloudflare-claire
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src”). cloudflare-claire
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src”).
cloudflare-claire:1
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src”). cloudflare-claire
1527001234164	addons.xpi	WARN	Failed to remove temporary file C:\Users\ALEX~1\AppData\Local\Temp\tmp-pls.xpi for addon https://addons.mozilla.org/firefox/downloads/file/872204/claire-0.11.1-an+fx.xpi?src=dp-btn-primary: [Exception... "Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIFile.remove]"  nsresult: "0x80520015 (NS_ERROR_FILE_ACCESS_DENIED)"  location: "JS frame :: resource://gre/modules/addons/XPIInstall.jsm :: removeTemporaryFile :: line 1498"  data: no] Stack trace: removeTemporaryFile()@resource://gre/modules/addons/XPIInstall.jsm:1498
startInstall/<()@resource://gre/modules/addons/XPIInstall.jsm:1790
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: ;undefined. claire:1

**Comment by seanmmitchell** [comment]
Claire has been deprecated by **Optics**, which was launched with Manifest V3 and Firefox support.

## Downloads for Optics

[![Chrome Web Store](https://img.shields.io/chrome-web-store/v/mdjgbjnbdnhneejmmaabmccfehigbjbe.svg)](https://chrome.google.com/webstore/detail/optics/mdjgbjnbdnhneejmmaabmccfehigbjbe)
[![Firefox Add-ons](https://img.shields.io/amo/v/cloudflare-optics.svg)](https://addons.mozilla.org/firefox/addon/cloudflare-optics/)
