### ISSUE TITLE
Pop-up too small

### ISSUE THREAD

**Issue by grahamperrin** [cloudflare/claire#55]
With some browsers, it's necessary to scroll. 

Waterfox 56.2.1, for example: 

![2018-06-30 08 43 57](https://user-images.githubusercontent.com/192271/42123604-c1f4c0ee-7c4c-11e8-9313-0c64eaba482e.png)

![2018-06-30 08 44 26](https://user-images.githubusercontent.com/192271/42123603-c1c64c8c-7c4c-11e8-9302-e1160cecb170.png)

```text
$ pkg info waterfox | grep Version ; date ; uname -v
Version        : 56.2.1.19_2
Sat 30 Jun 2018 10:04:17 BST
FreeBSD 12.0-CURRENT #6 r335800: Sat Jun 30 03:35:14 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

Please, can you increase the size? Or are you constrained by what's possible with Mozilla code?

**Comment by seanmmitchell** [comment]
Claire has been deprecated by **Optics**, which was launched with Manifest V3 and Firefox support.

## Downloads for Optics

[![Chrome Web Store](https://img.shields.io/chrome-web-store/v/mdjgbjnbdnhneejmmaabmccfehigbjbe.svg)](https://chrome.google.com/webstore/detail/optics/mdjgbjnbdnhneejmmaabmccfehigbjbe)
[![Firefox Add-ons](https://img.shields.io/amo/v/cloudflare-optics.svg)](https://addons.mozilla.org/firefox/addon/cloudflare-optics/)
