### ISSUE TITLE
Mysterious grey

### ISSUE THREAD

**Issue by grahamperrin** [cloudflare/claire#56]
Please, what's the meaning of a grey cloud icon? 

At https://www.onelogin.com/press-center/press-releases/onelogin-and-cloudflare-collaborate-to-extend-zero-trust-security-across-hybrid-environments for example.

**Comment by judge2020** [comment]
Grey means no features that Claire detects (HTTP2, Cloudflare, railgun and IPv6) are present.

You can also check if a website is on Cloudflare by visiting `/cdn-cgi/trace`, eg https://www.onelogin.com/cdn-cgi/trace is 404 while https://cloudflare.com/cdn-cgi/trace shows connection info.

**Comment by seanmmitchell** [comment]
Claire has been deprecated by **Optics**, which was launched with Manifest V3 and Firefox support.

## Downloads for Optics

[![Chrome Web Store](https://img.shields.io/chrome-web-store/v/mdjgbjnbdnhneejmmaabmccfehigbjbe.svg)](https://chrome.google.com/webstore/detail/optics/mdjgbjnbdnhneejmmaabmccfehigbjbe)
[![Firefox Add-ons](https://img.shields.io/amo/v/cloudflare-optics.svg)](https://addons.mozilla.org/firefox/addon/cloudflare-optics/)
