### ISSUE TITLE
Cloudflare Community incorrectly shows grey icon

### ISSUE THREAD

**Issue by judge2020** [cloudflare/claire#58]
On https://community.cloudflare.com, Claire shows a grey cloud and does not indicate Cloudflare, even though Cloudflare information is available on the [trace page](https://community.cloudflare.com/cdn-cgi/trace), and the website is serving HTTP2 and ipv6.

This may be an issue with the main request being issued from a service worker - this shows up for me upon a refresh in chrome:

![image](https://user-images.githubusercontent.com/8601934/44127715-a3ad070c-a00c-11e8-9ecc-a1f652a9aae6.png)

**Comment by seanmmitchell** [comment]
Claire has been deprecated by **Optics**, which was launched with Manifest V3 and Firefox support.

## Downloads for Optics

[![Chrome Web Store](https://img.shields.io/chrome-web-store/v/mdjgbjnbdnhneejmmaabmccfehigbjbe.svg)](https://chrome.google.com/webstore/detail/optics/mdjgbjnbdnhneejmmaabmccfehigbjbe)
[![Firefox Add-ons](https://img.shields.io/amo/v/cloudflare-optics.svg)](https://addons.mozilla.org/firefox/addon/cloudflare-optics/)
