### ISSUE TITLE
ZDM is missing from `airport.js`

### ISSUE THREAD

**Issue by rommycf** [cloudflare/claire#60]
Hello,

we're getting a report that one of Cloudflare new data centre (ZDM) is not available on airport.js

Thank you.

**Comment by ram-nadella** [comment]
@rommycf airport data is pulled from https://github.com/ram-nadella/airport-codes

Do you want to attempt sending a PR there to update it and then the equivalent file could be updated here in this repo after.

**Comment by seanmmitchell** [comment]
Claire has been deprecated by **Optics**, which was launched with Manifest V3 and Firefox support.

## Downloads for Optics

[![Chrome Web Store](https://img.shields.io/chrome-web-store/v/mdjgbjnbdnhneejmmaabmccfehigbjbe.svg)](https://chrome.google.com/webstore/detail/optics/mdjgbjnbdnhneejmmaabmccfehigbjbe)
[![Firefox Add-ons](https://img.shields.io/amo/v/cloudflare-optics.svg)](https://addons.mozilla.org/firefox/addon/cloudflare-optics/)
