### ISSUE TITLE
Railgun metrics don't look correct

### ISSUE THREAD

**Issue by Daniel15** [cloudflare/claire#61]
I'm using Railgun on https://dnstools.ws/ and Claire is showing odd data:

> Railgun ID: direct
> Compression: NaN%
> Time: newsec

**Comment by gitforwebwork** [comment]
And the Railgun indicator is red.

**Comment by seanmmitchell** [comment]
Claire has been deprecated by **Optics**, which was launched with Manifest V3 and Firefox support.

## Downloads for Optics

[![Chrome Web Store](https://img.shields.io/chrome-web-store/v/mdjgbjnbdnhneejmmaabmccfehigbjbe.svg)](https://chrome.google.com/webstore/detail/optics/mdjgbjnbdnhneejmmaabmccfehigbjbe)
[![Firefox Add-ons](https://img.shields.io/amo/v/cloudflare-optics.svg)](https://addons.mozilla.org/firefox/addon/cloudflare-optics/)
