### ISSUE TITLE
Claire no longer appears in the Firefox Add-In List

### ISSUE THREAD

**Issue by agador** [cloudflare/claire#62]
It appears that Claire has been ejected from Mozilla's Firefox Add-In list.

**Comment by Foorack** [comment]
@terinjokes Do you know why the extension has been removed?

**Comment by terinjokes** [comment]
It was removed for new rules around which JavaScript constructs we're allowed to use, along with distributing via a module built with Webpack.

**Comment by seanmmitchell** [comment]
Claire has been deprecated by **Optics**, which was launched with Manifest V3 and Firefox support.

## Downloads for Optics

[![Chrome Web Store](https://img.shields.io/chrome-web-store/v/mdjgbjnbdnhneejmmaabmccfehigbjbe.svg)](https://chrome.google.com/webstore/detail/optics/mdjgbjnbdnhneejmmaabmccfehigbjbe)
[![Firefox Add-ons](https://img.shields.io/amo/v/cloudflare-optics.svg)](https://addons.mozilla.org/firefox/addon/cloudflare-optics/)
