### ISSUE TITLE
Display Window Performance Timings

### ISSUE THREAD

**Issue by adrianmace** [cloudflare/claire#81]
This extension is great and I use it daily. It would be fantastic to extend it further and display performance timings as reported by the browser, to avoid having to go into the DevTools and reload the page to get access to this info.

Timings such as DNS resolution, TTFB, first print, etc.

**Comment by seanmmitchell** [comment]
Claire has been deprecated by **Optics**, which was launched with Manifest V3 and Firefox support.

## Downloads for Optics

[![Chrome Web Store](https://img.shields.io/chrome-web-store/v/mdjgbjnbdnhneejmmaabmccfehigbjbe.svg)](https://chrome.google.com/webstore/detail/optics/mdjgbjnbdnhneejmmaabmccfehigbjbe)
[![Firefox Add-ons](https://img.shields.io/amo/v/cloudflare-optics.svg)](https://addons.mozilla.org/firefox/addon/cloudflare-optics/)
