### ISSUE TITLE
Add support for Brave Browser

### ISSUE THREAD

**Issue by fharper** [cloudflare/claire#82]
Usually extensions for Chrome works perfectly on Brave, but it's not the case for this one. I assume the URL bar object isn't the same. It would be nice to make it work for Brave also.

**Comment by seanmmitchell** [comment]
Claire has been deprecated by **Optics**, which was launched with Manifest V3 and Firefox support.

## Downloads for Optics

[![Chrome Web Store](https://img.shields.io/chrome-web-store/v/mdjgbjnbdnhneejmmaabmccfehigbjbe.svg)](https://chrome.google.com/webstore/detail/optics/mdjgbjnbdnhneejmmaabmccfehigbjbe)
[![Firefox Add-ons](https://img.shields.io/amo/v/cloudflare-optics.svg)](https://addons.mozilla.org/firefox/addon/cloudflare-optics/)
